sudo: required
services:
  - docker

before_install:
  - docker build -t mi11/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mi11/react-test npm run test -- --watchAll=false

after_success:
  - docker build -t mi11/multi-client ./client
  - docker build -t mi11/multi-nginx ./nginx
  - docker build -t mi11/multi-server ./server
  - docker build -t mi11/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mi11/multi-client
  - docker push mi11/multi-nginx
  - docker push mi11/multi-server
  - docker push mi11/multi-worker
